# RootmeKit 设备配置
# 用户只需填写 rom_url，其余全自动检测
# 修改此文件后推送到 main 分支，GitHub Action 自动构建

devices:
  # 示例设备 - 替换为您自己的 ROM 下载链接
  - rom_url: "https://gauss-compota-c-cn.allawnfs.com/remove-24b572ce99b11baa0fd437dddf96fc64/g-10eab6008d5642cf42abd2aa41f847cb/component-ota/26/04/13/2abf9491f2104f5f851aa093596f7c20.zip?sign=bb3aecf226f4e95a02b6dd13840002e2&t=6a55ed4f&AWSAccessKeyId=ayjy7KyLVHvDqDax6_KqJgtBeORTJARg9MSGiL66&Expires=1784018007&Signature=xXUTx3mgEPZHo1wcLdT%2BhXfxxE4%3D"
    # kernel_partition: 内核所在分区
    #   老手机 (Android 12 及更早): boot
    #   新手机 (Android 13+ GKI):     init_boot
    #   不填则自动尝试 init_boot -> boot -> vendor_boot
    kernel_partition: "boot"
    # name: 可选，默认从 ROM 文件名自动生成
    # manual_offsets: 可选，自动提取失败时手动指定
    #   KIMAGE_TEXT_BASE: "0xFFFFFFC080000000"
    #   INIT_TASK_OFF: "0x0"
