"""Stage 5: Calculate all offsets and generate target.h / offsets.h.

Finds required symbols, calculates struct offsets, determines memory layout,
and renders C header files using Jinja2 templates.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

from jinja2 import Template

from ..utils.elf_utils import find_kimage_base

logger = logging.getLogger(__name__)

# ── Required symbols ──────────────────────────────────────────────────────

REQUIRED_SYMBOLS: dict[str, list[str]] = {
    "INIT_TASK": ["init_task"],
    "INIT_CRED": ["init_cred"],
    "SELINUX_ENFORCING": ["selinux_enforcing", "selinux_state"],
    "ANON_PIPE_BUF_OPS": ["anon_pipe_buf_ops"],
    "KMALLOC_CACHES": ["kmalloc_caches"],
    "NFULNL_LOGGER": ["nfulnl_logger"],
    "SECURITY_HOOK_HEADS": ["security_hook_heads"],
    "DMA_HEAP_FOPS": ["dma_heap_fops", "dma_buf_fops"],
    "ASHMEM_FOPS": ["ashmem_fops"],
    "KIMAGE_TEXT_BASE": ["_stext", "_text", "__init_begin"],
}

# ── Required struct fields ────────────────────────────────────────────────

REQUIRED_STRUCT_FIELDS: dict[str, list[str]] = {
    "task_struct": ["cred", "pid", "tasks", "seccomp", "real_cred", "flags"],
    "cred": ["uid", "gid", "euid", "egid", "cap_effective", "cap_inheritable",
             "cap_permitted", "cap_bset", "security"],
    "pipe_buffer": ["page", "ops", "flags", "private"],
    "mm_struct": ["start_code", "end_code", "start_data", "end_data",
                  "start_brk", "brk", "start_stack"],
}

# ── Memory layout templates ───────────────────────────────────────────────

TARGET_H_TEMPLATE = Template("""\
/* Auto-generated by RootmeKit - DO NOT EDIT */
/* Device: {{ device_name }} */

#ifndef _TARGET_H_
#define _TARGET_H_

{% if offsets %}
/* Symbol addresses */
{% for name, value in offsets.items() %}
#define {{ name }}\t0x{{ "0" if value == 0 else "%x" | format(value) }}
{% endfor %}
{% endif %}

{% if layout %}
/* Memory layout */
{% for name, value in layout.items() %}
#define {{ name }}\t0x{{ "0" if value == 0 else "%x" | format(value) }}
{% endfor %}
{% endif %}

{% if struct_offsets %}
/* Struct field offsets */
{% for struct_name, fields in struct_offsets.items() %}
/* {{ struct_name }} */
{% for field_name, offset in fields.items() %}
#define {{ struct_name }}_{{ field_name }}\t{{ offset }}
{% endfor %}
{% endfor %}
{% endif %}

/* Memory type */
#define MEMORY_TYPE_{{ memory_type | upper }}\t1

#endif /* _TARGET_H_ */
""")

OFFSETS_H_TEMPLATE = Template("""\
/* Auto-generated by RootmeKit - DO NOT EDIT */
/* Device: {{ device_name }} */
/* Offset source tracking: {{ offset_sources | tojson }} */

#ifndef _OFFSETS_H_
#define _OFFSETS_H_

{% if offsets %}
/* Resolved symbol offsets */
{% for name, info in offsets.items() %}
/* Source: {{ info.source }} */
#define {{ name }}\t0x{{ "0" if info.value == 0 else "%x" | format(info.value) }}

{% endfor %}
{% endif %}

{% if struct_offsets %}
/* Struct field offsets with source tracking */
{% for struct_name, fields in struct_offsets.items() %}
/* {{ struct_name }} */
{% for field_name, info in fields.items() %}
/* Source: {{ info.source }} */
#define {{ struct_name }}_{{ field_name }}\t{{ info.value }}

{% endfor %}
{% endfor %}
{% endif %}

/* Confidence report */
{% if confidence_report %}
{% for key, value in confidence_report.items() %}
/* {{ key }}: {{ value }} */
{% endfor %}
{% endif %}

#endif /* _OFFSETS_H_ */
""")


def detect_memory_type(
    kernel_version: str | None,
    is_gki: bool,
    symbols: dict[str, int],
) -> str:
    """Determine memory type: ashmem vs dma_heap.

    Rules:
    - kernel >= 6.1 AND no ashmem_fops symbol → dma_heap
    - kernel < 6.1 OR ashmem_fops available → ashmem
    - Default to dma_heap for GKI, ashmem for non-GKI

    Returns:
        'dma_heap' or 'ashmem'
    """
    has_ashmem = "ashmem_fops" in symbols

    if kernel_version:
        m = re.match(r"(\d+)\.(\d+)", kernel_version)
        if m:
            major = int(m.group(1))
            minor = int(m.group(2))
            if major > 6 or (major == 6 and minor >= 1):
                if not has_ashmem:
                    logger.info("Memory type: dma_heap (kernel >= 6.1, no ashmem)")
                    return "dma_heap"
                else:
                    logger.info("Memory type: dma_heap (kernel >= 6.1, ashmem also available)")
                    return "dma_heap"

    if is_gki:
        logger.info("Memory type: dma_heap (GKI default)")
        return "dma_heap"

    if has_ashmem:
        logger.info("Memory type: ashmem (ashmem_fops found, non-GKI)")
        return "ashmem"

    # Default
    logger.info("Memory type: dma_heap (default)")
    return "dma_heap"


def _resolve_symbol(
    name: str,
    candidates: list[str],
    symbols: dict[str, int],
    manual_offsets: dict[str, int] | None = None,
) -> dict[str, Any]:
    """Resolve a symbol from candidates list, tracking the source.

    Returns:
        dict with keys: value (int), source (str), found (bool)
    """
    # Check manual offsets first
    if manual_offsets:
        for candidate in candidates:
            if candidate in manual_offsets:
                return {
                    "value": manual_offsets[candidate],
                    "source": f"manual:{candidate}",
                    "found": True,
                }

    # Check recovered symbols
    for candidate in candidates:
        if candidate in symbols:
            return {
                "value": symbols[candidate],
                "source": f"symbol:{candidate}",
                "found": True,
            }

    logger.warning("Could not resolve symbol %s (tried: %s)", name, ", ".join(candidates))
    return {"value": 0, "source": "missing", "found": False}


def _resolve_struct_offsets(
    struct_name: str,
    required_fields: list[str],
    btf_structs: dict[str, dict[str, int]],
    manual_offsets: dict[str, int] | None = None,
) -> dict[str, dict[str, Any]]:
    """Resolve struct field offsets from BTF or manual offsets.

    Returns:
        dict mapping field_name -> {value, source, found}
    """
    result: dict[str, dict[str, Any]] = {}
    btf_fields = btf_structs.get(struct_name, {})

    for field in required_fields:
        # Check manual offsets first (key format: struct_name.field_name)
        if manual_offsets:
            manual_key = f"{struct_name}.{field}"
            if manual_key in manual_offsets:
                result[field] = {
                    "value": manual_offsets[manual_key],
                    "source": f"manual:{manual_key}",
                    "found": True,
                }
                continue

        # Check BTF offsets
        if field in btf_fields:
            result[field] = {
                "value": btf_fields[field],
                "source": f"btf:{struct_name}.{field}",
                "found": True,
            }
            continue

        # Not found
        logger.warning("Missing offset: %s.%s", struct_name, field)
        result[field] = {"value": 0, "source": "missing", "found": False}

    return result


def _calculate_memory_layout(
    symbols: dict[str, int],
    arch: str,
    va_bits: int | None = None,
) -> dict[str, int]:
    """Calculate memory layout constants for the target architecture.

    Currently only supports arm64/aarch64 fully.

    Returns:
        dict with layout constants (KIMAGE_TEXT_BASE, VMEMMAP_START,
        PAGE_OFFSET, MODULES_VADDR, etc.)
    """
    layout: dict[str, int] = {}

    if arch not in ("aarch64", "arm64"):
        logger.warning("Memory layout calculation only fully supported for aarch64, "
                        "got: %s", arch)

    # KIMAGE_TEXT_BASE
    kimage_base = find_kimage_base(symbols)
    if kimage_base is not None:
        layout["KIMAGE_TEXT_BASE"] = kimage_base
    else:
        # Default for arm64
        layout["KIMAGE_TEXT_BASE"] = 0xFFFFFF8008080000
        logger.warning("Using default KIMAGE_TEXT_BASE for arm64")

    if arch in ("aarch64", "arm64"):
        if va_bits is None:
            va_bits = 48  # Default for arm64
            # Try to detect from symbol addresses
            if symbols:
                max_addr = max(symbols.values())
                if max_addr < 0x100000000000:
                    va_bits = 39

        layout["VA_BITS"] = va_bits

        # VMEMMAP_START = -(1 << (VA_BITS - 6)) for arm64
        # Represented as unsigned 64-bit
        vmemmap_start = (1 << 64) - (1 << (va_bits - 6))
        layout["VMEMMAP_START"] = vmemmap_start

        # PAGE_OFFSET = -(1 << VA_BITS) for arm64
        page_offset = (1 << 64) - (1 << va_bits)
        layout["PAGE_OFFSET"] = page_offset

        # MODULES_VADDR = PAGE_OFFSET + 0x800000 for arm64
        layout["MODULES_VADDR"] = page_offset + 0x800000

        logger.info(
            "Memory layout: VA_BITS=%d, KIMAGE_TEXT_BASE=0x%x, "
            "PAGE_OFFSET=0x%x, VMEMMAP_START=0x%x, MODULES_VADDR=0x%x",
            va_bits, layout["KIMAGE_TEXT_BASE"], page_offset,
            vmemmap_start, layout["MODULES_VADDR"],
        )
    else:
        # x86_64 defaults
        layout["VA_BITS"] = 48
        layout["PAGE_OFFSET"] = 0xFFFF888000000000
        layout["VMEMMAP_START"] = 0xFFFFEA0000000000
        layout["MODULES_VADDR"] = 0xFFFFFFFFA0000000

    return layout


def calculate_offsets(
    symbols: dict[str, int],
    btf_structs: dict[str, dict[str, int]],
    kernel_version: str | None,
    arch: str,
    is_gki: bool,
    va_bits: int | None = None,
    manual_offsets: dict[str, int] | None = None,
) -> dict[str, Any]:
    """Main offset calculation.

    Args:
        symbols: Recovered symbol dict.
        btf_structs: BTF struct offsets.
        kernel_version: Kernel version string.
        arch: Architecture string.
        is_gki: Whether this is a GKI kernel.
        va_bits: VA_BITS if known.
        manual_offsets: Optional manual overrides.

    Returns:
        dict with all calculated offsets, layout, sources, and confidence.
    """
    # Resolve required symbols
    resolved_symbols: dict[str, dict[str, Any]] = {}
    simple_offsets: dict[str, int] = {}

    for name, candidates in REQUIRED_SYMBOLS.items():
        info = _resolve_symbol(name, candidates, symbols, manual_offsets)
        resolved_symbols[name] = info
        simple_offsets[name] = info["value"]

    # Resolve struct field offsets
    resolved_structs: dict[str, dict[str, dict[str, Any]]] = {}
    flat_struct_offsets: dict[str, dict[str, int]] = {}

    for struct_name, fields in REQUIRED_STRUCT_FIELDS.items():
        resolved = _resolve_struct_offsets(struct_name, fields, btf_structs, manual_offsets)
        resolved_structs[struct_name] = resolved
        flat_struct_offsets[struct_name] = {f: v["value"] for f, v in resolved.items()}

    # Determine memory type
    memory_type = detect_memory_type(kernel_version, is_gki, symbols)

    # Calculate memory layout
    layout = _calculate_memory_layout(symbols, arch, va_bits)

    # Build confidence report
    total_symbols = len(resolved_symbols)
    found_symbols = sum(1 for v in resolved_symbols.values() if v["found"])
    total_fields = sum(len(v) for v in resolved_structs.values())
    found_fields = sum(
        1 for s in resolved_structs.values() for f in s.values() if f["found"]
    )

    confidence = {
        "symbols_found": f"{found_symbols}/{total_symbols}",
        "fields_found": f"{found_fields}/{total_fields}",
        "symbol_recovery_confidence": "high" if found_symbols == total_symbols else
                                       "medium" if found_symbols > total_symbols // 2 else "low",
        "offset_confidence": "high" if found_fields == total_fields else
                             "medium" if found_fields > total_fields // 2 else "low",
        "memory_type": memory_type,
        "has_btf": bool(btf_structs),
    }

    # Build offset source tracking
    offset_sources: dict[str, str] = {}
    for name, info in resolved_symbols.items():
        offset_sources[name] = info["source"]
    for struct_name, fields in resolved_structs.items():
        for field_name, info in fields.items():
            offset_sources[f"{struct_name}.{field_name}"] = info["source"]

    return {
        "offsets": resolved_symbols,
        "simple_offsets": simple_offsets,
        "struct_offsets": resolved_structs,
        "flat_struct_offsets": flat_struct_offsets,
        "layout": layout,
        "memory_type": memory_type,
        "offset_sources": offset_sources,
        "confidence_report": confidence,
    }


def generate_target_h(
    offsets: dict[str, int],
    layout: dict[str, int],
    struct_offsets: dict[str, dict[str, int]],
    memory_type: str,
    output_dir: str | Path,
    device_name: str,
) -> Path:
    """Render target.h using Jinja2 template.

    Returns:
        Path to the generated target.h file.
    """
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    target_h_path = out_dir / "target.h"

    content = TARGET_H_TEMPLATE.render(
        device_name=device_name,
        offsets=offsets,
        layout=layout,
        struct_offsets=struct_offsets,
        memory_type=memory_type,
    )

    target_h_path.write_text(content)
    logger.info("Generated target.h: %s", target_h_path)
    return target_h_path


def generate_offsets_h(
    offsets: dict[str, dict[str, Any]],
    struct_offsets: dict[str, dict[str, dict[str, Any]]],
    offset_sources: dict[str, str],
    confidence_report: dict[str, Any],
    output_dir: str | Path,
    device_name: str,
) -> Path:
    """Render offsets.h with source tracking.

    Returns:
        Path to the generated offsets.h file.
    """
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    offsets_h_path = out_dir / "offsets.h"

    content = OFFSETS_H_TEMPLATE.render(
        device_name=device_name,
        offsets=offsets,
        struct_offsets=struct_offsets,
        offset_sources=offset_sources,
        confidence_report=confidence_report,
    )

    offsets_h_path.write_text(content)
    logger.info("Generated offsets.h: %s", offsets_h_path)
    return offsets_h_path


def run(prev_result: dict[str, Any], work_dir: str | Path) -> dict[str, Any]:
    """Main entry point for offset calculation stage.

    Args:
        prev_result: Combined results from previous stages. Expected keys:
            'symbols', 'has_btf', 'btf_structs', 'kernel_version', 'arch',
            'kernel_is_gki', and optionally 'va_bits', 'manual_offsets'.
        work_dir: Working directory.

    Returns:
        dict with all offsets, paths to generated headers, and confidence report.
    """
    work = Path(work_dir)
    output_dir = work / "offsets"

    symbols = prev_result.get("symbols", {})
    btf_structs = prev_result.get("btf_structs", {})
    kernel_version = prev_result.get("kernel_version")
    arch = prev_result.get("arch", "aarch64")
    is_gki = prev_result.get("kernel_is_gki", False)
    va_bits = prev_result.get("va_bits")
    manual_offsets = prev_result.get("manual_offsets")
    device_name = prev_result.get("device_name", "unknown")

    # Calculate all offsets
    calc = calculate_offsets(
        symbols=symbols,
        btf_structs=btf_structs,
        kernel_version=kernel_version,
        arch=arch,
        is_gki=is_gki,
        va_bits=va_bits,
        manual_offsets=manual_offsets,
    )

    # Generate target.h
    target_h_path = generate_target_h(
        offsets=calc["simple_offsets"],
        layout=calc["layout"],
        struct_offsets=calc["flat_struct_offsets"],
        memory_type=calc["memory_type"],
        output_dir=output_dir,
        device_name=device_name,
    )

    # Generate offsets.h
    offsets_h_path = generate_offsets_h(
        offsets=calc["offsets"],
        struct_offsets=calc["struct_offsets"],
        offset_sources=calc["offset_sources"],
        confidence_report=calc["confidence_report"],
        output_dir=output_dir,
        device_name=device_name,
    )

    return {
        "target_h_path": target_h_path,
        "offsets_h_path": offsets_h_path,
        "offsets": calc["simple_offsets"],
        "struct_offsets": calc["flat_struct_offsets"],
        "layout": calc["layout"],
        "memory_type": calc["memory_type"],
        "offset_sources": calc["offset_sources"],
        "confidence_report": calc["confidence_report"],
    }
